param(
    [string]$WorkRoot = "",
    # 不寫入快照（僅測試／極少數 CI）；預設一律寫入 agency-os/.agency-state/open-tasks-snapshot.md
    [switch]$NoSnapshot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Windows PowerShell 5.x consoles often default to a legacy code page; TASKS.md is UTF-8.
if ($PSVersionTable.PSVersion.Major -lt 7) {
    try {
        chcp 65001 | Out-Null
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $OutputEncoding = [System.Text.Encoding]::UTF8
    } catch {}
}

if ($WorkRoot) {
    $WorkRoot = (Resolve-Path $WorkRoot).Path
} elseif ($PSScriptRoot) {
    $WorkRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
} else {
    $WorkRoot = (Get-Location).Path
}

$tasksPath = Join-Path $WorkRoot "agency-os\TASKS.md"
if (-not (Test-Path -LiteralPath $tasksPath)) {
    Write-Host "print-open-tasks: TASKS.md not found at $tasksPath" -ForegroundColor Yellow
    exit 0
}

$utf8 = [System.Text.UTF8Encoding]::new($false)
$lines = @([System.IO.File]::ReadAllLines($tasksPath, $utf8))
$section = "(prologue — before first ##)"
$rxOpen = [regex]'^\s*-\s+\[\s+\]\s+'
$rxHeading = [regex]'^##\s+'

$items = New-Object System.Collections.Generic.List[object]

Write-Host ""
Write-Host "== Open tasks in agency-os/TASKS.md (all unchecked - [ ]) ==" -ForegroundColor Cyan

$count = 0
foreach ($line in $lines) {
    if ($rxHeading.IsMatch($line)) {
        $section = $line.Trim()
        continue
    }
    if ($rxOpen.IsMatch($line)) {
        $count++
        $trim = $line.Trim()
        Write-Host ("  [{0}] {1}" -f $section, $trim)
        $items.Add([pscustomobject]@{ Section = $section; Line = $trim })
    }
}

if ($count -eq 0) {
    Write-Host "  (none)" -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host ("Total open: {0}" -f $count) -ForegroundColor DarkGray
}

if (-not $NoSnapshot) {
    $stateDir = Join-Path $WorkRoot "agency-os\.agency-state"
    $null = New-Item -ItemType Directory -Force -Path $stateDir
    $snapshotPath = Join-Path $stateDir "open-tasks-snapshot.md"

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("# Open tasks snapshot")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("> Auto-generated by ``scripts/print-open-tasks.ps1``. **Gitignored.**")
    [void]$sb.AppendLine("> Agents: after ``ao-resume.ps1`` exit 0, **read this file** then cross-check ``agency-os/TASKS.md``. Chat must still list every ``- [ ]`` per ``30-resume-keyword.mdc``.")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine(("Generated (UTC): {0}" -f [DateTime]::UtcNow.ToString("o")))
    [void]$sb.AppendLine(("Source: agency-os/TASKS.md"))
    [void]$sb.AppendLine(("Total open: {0}" -f $count))
    [void]$sb.AppendLine("")

    if ($count -eq 0) {
        [void]$sb.AppendLine("_(none)_")
        [void]$sb.AppendLine("")
    } else {
        $bySection = $items | Group-Object -Property Section
        foreach ($g in $bySection) {
            [void]$sb.AppendLine(("## {0}" -f $g.Name))
            foreach ($it in $g.Group) {
                [void]$sb.AppendLine($it.Line)
            }
            [void]$sb.AppendLine("")
        }
    }

    [System.IO.File]::WriteAllText($snapshotPath, $sb.ToString(), $utf8)
    Write-Host ("open-tasks snapshot: {0}" -f $snapshotPath) -ForegroundColor DarkGray
}

exit 0
